services:
  task-management-api:
    depends_on:
      - task-management-db
    ports:
      - 8082:8080
    build:
      context: ./api
      target: debug
    restart: always
    container_name: "task-management-api"
    env_file: ./api/.env
    volumes:
      - ./api:/app
    tty: true

  task-management-db:
    image: postgres:17-bookworm
    container_name: task-management-db
    restart: unless-stopped
    ports:
      - 15434:5432
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      timeout: 20s
      interval: 3s
      retries: 3

volumes:
  db-data:
