services:
  todo-app-api:
    depends_on:
      - todo-app-db
    ports:
      - 8082:8080
    build:
      context: .
      target: debug
    restart: always
    container_name: "todo-app-api"
    env_file: .env
    volumes:
      - .:/app
    tty: true

  todo-app-db:
    image: postgres:17-bookworm
    container_name: todo-app-db
    restart: unless-stopped
    ports:
      - 15434:5432
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - todo-app-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      timeout: 20s
      interval: 3s
      retries: 3

volumes:
  todo-app-db-data:
